spring.application.name=movies
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-pxfedx63ys2p17i6.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://movie-search-api

omdb.api.url=https://www.omdbapi.com
omdb.api.key=${OMDB_API_KEY}
